### ISSUE TITLE
Coverage reporting unnecessary for several build stages?

### ISSUE THREAD

**Issue by rmjordas** [projectunic0rn/pub#158]
The CI will run at least three (3) jobs for a specific build (more depending on the type, i.e. `branch`, `pull_request`, etc.):

- `npm run typecheck`
- `npm run lint`
- `npm test`

But if any of them is successful, the will still push a report via the `codecov` package. This is an example for Job `#822.1` which simply runs `npm run typecheck`:

![Screenshot_2020-01-23 Job #822 1 - projectunic0rn pub - Travis CI](https://user-images.githubusercontent.com/27814962/72951682-30649980-3d87-11ea-828e-1bf23835f7ed.png)

Notice the part where it says:

```
==> Scanning for reports

    X Failed to read file at 
```

It didn't see any report because `npm test` was not run in this stage.

So, I think this is the reason why we have this:

![Screenshot_2020-01-23 Fix TagTemplate pagination prefix by rmjordas · Pull Request #157 · projectunic0rn pub](https://user-images.githubusercontent.com/27814962/72951776-889b9b80-3d87-11ea-8b19-e35b666780b6.png)

@roymoran Will coverage reporting still work if  we just run the `codecov` only on the stage that runs `npm test`?

**Comment by roymoran** [comment]
yeah you're right. it doesn't find the generated coverage report because those other stages/jobs don't run the test step. I'm working on adding the app version to the footer now and will make an adjustment to the travis file on that PR.
